name: reset

on:
  workflow_dispatch:
  schedule:
    - cron: '13 2 1,6,11,16,21,26 * *'
# Reset the database every five days to its original state
# This happens at 2:13 AM on the 1st, 6th, 11th, 16th, 21st, and 26th of each month
# This action deletes all users, their ratings, and recommendations for the purpose
# of containing spam and abuse in this small demo project

jobs:
  update:
    name: reset database
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Reset database and set inital recommendations
        run: |
          python reset_database.py
          python update_database.py
        env:
          POSTGRES_USER: "${{ secrets.POSTGRES_USER }}"
          POSTGRES_PASSWORD: "${{ secrets.POSTGRES_PASSWORD }}"
          POSTGRES_HOST: "${{ secrets.POSTGRES_HOST }}"
          POSTGRES_DB: "${{ secrets.POSTGRES_DB }}"
